### ISSUE TITLE
Can gotbeef web app connect to test or dev?

### ISSUE THREAD

**Issue by georgescharlesbrain** [juzybits/polymedia-gotbeef#4]
I'm trying to connect my wallet (ethos and sui), which are connected to test, to the web Dapp.
It seems the app always defaults to mainnet.
On my own deployment on render.com, I made the toggle visible, but it seems the toggle doesn't work.
Is there something in the 
	@polymedia/react-components
	@polymedia/webutils
packages that blocks the switching of networks when the web app is not run on localhost?

**Comment by juzybits** [comment]
Network switching works, but localnet only gets included in the network selector when the website is running on localhost. This made sense back when Sui was in the testnet stage and the selector was shown in production so people could choose devnet or testnet. But now that Sui is on mainnet, the network selector is no longer shown in production - only on localhost. So I think it's fine now to include the localhost option in the selector. I made a change to allow that:
https://github.com/juzybits/polymedia-webutils/commit/dbb5092fc483b78bd0aafd3be88610d3dd61124c

Also I redeployed the package on devnet and testnet, because the original deployments have been wiped out by previous network upgrades:
https://github.com/juzybits/polymedia-gotbeef/commit/d906bb37d7ae88b66009146eb1c28c4db6a196ec

Please upgrade your dependencies and let me know if that works for you now.

**Comment by juzybits** [comment]
You'll also have to edit these two lines if you want to switch networks somewhere other than localhost:

https://github.com/juzybits/polymedia-gotbeef/blob/main/web/src/js/App.tsx#L23
https://github.com/juzybits/polymedia-gotbeef/blob/main/web/src/js/App.tsx#L27

**Comment by georgescharlesbrain** [comment]
const showNetworkSelector = true;
const network = loadNetwork();  
  
Did the trick. Thx for your patience and help.
